# Sinhala→English NMT Hallucination Detection

Token-level detector training, source-ablation control, NMT benchmarking and ensemble evaluation.

**Input:** `synthetic_hallucinations_balanced.csv` from *Dataset Generation.ipynb*.
**Outputs (in `OUT_DIR`):** split CSVs, `table3_detector.csv`, `table_source_ablation.csv`, `table5_ensemble.csv`, `benchmark_outputs.csv` (consumed by *External Validation.ipynb*), `table4_partitions.csv`, saved detector checkpoints.

## 1. Environment Setup

Install and pin all dependencies, then restart the kernel so the new binaries are loaded cleanly. The `numpy<2.0` pin is required because `transformers 4.x` is not yet compatible with NumPy 2.

In [ ]:
# Uninstall existing torch/numpy to avoid stale binaries after version switch.
!pip uninstall -y torch torchvision torchaudio numpy

# Install the exact cu126 builds. Pinning versions keeps the run reproducible.
!pip install -q torch==2.9.0 torchvision==0.24.0 torchaudio==2.9.0 \
    --index-url https://download.pytorch.org/whl/cu126

# NMT dependencies. numpy<2.0 is pinned because transformers 4.x breaks on numpy 2.
!pip install -q transformers==4.57.1 "numpy<2.0" datasets accelerate sacremoses sentencepiece

# Kernel restart is needed so the newly installed binaries are actually loaded.
import os
os._exit(0)

Found existing installation: torch 2.10.0+cu128
Uninstalling torch-2.10.0+cu128:
  Successfully uninstalled torch-2.10.0+cu128
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128
Found existing installation: numpy 2.0.2
Uninstalling numpy-2.0.2:
  Successfully uninstalled numpy-2.0.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 104.3 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 161.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 174.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 76.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 99.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 122.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 91.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 72.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 110.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 108.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 146.3 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 225.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 832.9/832.9 MB 609.2 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 65.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 42.2 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 10.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 87.8 MB/s eta 0:00:00:00:0100:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
ydata-profiling 4.18.4 requires numpy<2.4,>=1.22, but you have numpy 2.5.2 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.2 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 719.5 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 93.9 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 84.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 867.8/867.8 kB 26.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 25.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
kaggle-environments 1.29.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cesium 0.12.4 requires numpy<3.0,>=2.0, but you have numpy 1.26.4 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.

### Configuration, Imports & Device

Training is pinned to a single GPU so the per-device batch size is the effective batch size (the earlier run silently used DataParallel on 2×T4, i.e. batch 16).

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"   # single GPU: batch size 8 is the real batch size

import gc, re, json, random, shutil, difflib
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}  ({torch.cuda.get_device_name(0) if DEVICE == 'cuda' else 'cpu'})")

# ── Configuration ─────────────────────────────────────────────────
DATASET_FILE = "/kaggle/input/datasets/navamobeysekara/final-synthetic/synthetic_hallucinations_balanced.csv"
OUT_DIR      = "/kaggle/working" if os.path.exists("/kaggle/working") else "."
MODEL_DIR    = os.path.join(OUT_DIR, "models")
os.makedirs(MODEL_DIR, exist_ok=True)

SPLIT_SEED   = 42                  # fixed: the test set is identical across training seeds
SEEDS        = [42, 43, 44]        # training seeds (report mean ± std)
DETECTORS    = {"mdeberta": "microsoft/mdeberta-v3-base", "xlmr": "xlm-roberta-base"}
PRIMARY      = "mdeberta"
PRIMARY_SEED = 42                  # checkpoint used for benchmarking & ensemble

LR, EPOCHS, BATCH = 2e-5, 6, 8
RESCUE_THR   = 0.80

RUN_TRAIN      = True   # Section 3
RUN_ABLATION   = True   # Section 4 (source-ablation control)
RUN_HYP_ONLY   = True   # Section 4 (hypothesis-only retrain)
RUN_AUGMENT    = False  # Section 4b (mismatch augmentation) — enable if the control shows weak source use
RUN_ENSEMBLE   = True   # Section 5
RUN_BENCHMARK  = True   # Section 6

def set_seed(seed):
    random.seed(seed); np.random.seed(seed)
    torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)

def free_gpu():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

Using device: cuda  (Tesla T4)

### Version Check

A quick printout of exact library versions. Run this after every kernel restart to confirm the environment matches expectations.

In [2]:
import sys
import torch
import re
import difflib
import numpy as np
import sklearn
import transformers

# Print exact versions so results can be reproduced on another machine.
print("--- ENVIRONMENT VERSIONS ---")
print(f"Python:       {sys.version.split()[0]}")
print(f"PyTorch:      {torch.__version__}")
print(f"NumPy:        {np.__version__}")
print(f"Scikit-Learn: {sklearn.__version__}")
print(f"Transformers: {transformers.__version__}")
print(f"re:           {getattr(re, '__version__', 'Standard Library')}")
print(f"difflib:      Standard Library")
print("----------------------------")

--- ENVIRONMENT VERSIONS ---
Python:       3.12.13
PyTorch:      2.9.0+cu126
NumPy:        1.26.4
Scikit-Learn: 1.6.1
Transformers: 4.57.1
re:           2.2.1
difflib:      Standard Library
----------------------------

## 2. Data Loading & Source-Grouped Split

The split is grouped by Sinhala source, so no source sentence appears in more than one of train / validation / test (the earlier row-level split put 73% of test rows' sources in training). Validation is used for checkpoint selection and threshold calibration; the test set is touched only for final reporting.

In [3]:
from sklearn.model_selection import GroupShuffleSplit

df_raw = pd.read_csv(DATASET_FILE)
n0 = len(df_raw)
df_full = df_raw.dropna(subset=["sinhala", "reference", "hypothesis"])
df_full = df_full[df_full["reference"].str.contains("[a-zA-Z]") &
                  df_full["hypothesis"].str.contains("[a-zA-Z]")].reset_index(drop=True)
print(f"Rows loaded: {n0}   after filtering: {len(df_full)}   dropped: {n0 - len(df_full)}")

def group_split(df, test_size=0.20, val_size=0.10, seed=SPLIT_SEED):
    g1 = GroupShuffleSplit(n_splits=1, test_size=test_size, random_state=seed)
    tr, te = next(g1.split(df, groups=df["sinhala"]))
    train, test = df.iloc[tr], df.iloc[te]
    g2 = GroupShuffleSplit(n_splits=1, test_size=val_size / (1 - test_size), random_state=seed)
    tr2, va = next(g2.split(train, groups=train["sinhala"]))
    train, val = train.iloc[tr2], train.iloc[va]
    assert not (set(train.sinhala) & set(test.sinhala)) and not (set(val.sinhala) & set(test.sinhala))
    return [d.reset_index(drop=True) for d in (train, val, test)]

train_df, val_df, test_df = group_split(df_full)
for name, d in [("train", train_df), ("val", val_df), ("test", test_df)]:
    d.to_csv(os.path.join(OUT_DIR, f"split_{name}.csv"), index=False)
    print(f"{name:>5}: {len(d):>5} rows  {d.sinhala.nunique():>5} sources  labels {d.label.value_counts().to_dict()}")

Rows loaded: 15000   after filtering: 15000   dropped: 0
train: 10486 rows   5197 sources  labels {0: 5248, 1: 5238}
  val:  1497 rows    743 sources  labels {0: 751, 1: 746}
 test:  3017 rows   1485 sources  labels {1: 1516, 0: 1501}

## 3. Token Labels, Encoding & Detector Training

**Labels.** `difflib.SequenceMatcher` aligns hypothesis and reference words; `insert`/`replace` words are candidate label 1. *Semantic rescue* (Ratcliff/Obershelp similarity ≥ 0.80 against the aligned reference span ± 3 words) downgrades candidates to 0, and is applied **only to rows containing high-temperature sampling** — deterministic corruptions are hallucinations by construction. (The previous rule compared against every reference word, which erased 93% of dependency-swap labels because the swapped words occur verbatim in the reference.) `source_mismatch` rows (Section 4b) are all-1.

**Encoding.** `[CLS] source [SEP] hypothesis [SEP]`, hypothesis tokenised word by word; the same `encode()` is used for training **and** inference. The source is truncated first so the hypothesis is never cut.

**Classifier.** 2-class softmax head with cross-entropy (Hugging Face token classification), argmax at inference.

**Protocol.** Every detector × seed is trained on train, selected on validation F1, and evaluated once on test. mDeBERTa and XLM-R go through exactly the same code.

In [4]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def norm_words(text):
    return re.sub(r"([.,!?()])", r" \1 ", str(text)).split()

def _sim(a, b):
    return difflib.SequenceMatcher(None, a.lower(), b.lower()).ratio()

def word_labels(reference, hypothesis, method, thr=RESCUE_THR, window=3):
    hyp = norm_words(hypothesis)
    if method == "source_mismatch":
        return hyp, [1] * len(hyp)
    ref = norm_words(reference)
    labels = [0] * len(hyp)
    use_rescue = "temp" in str(method).split(" + ")
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, ref, hyp).get_opcodes():
        if tag not in ("insert", "replace"):
            continue
        span = ref[max(0, i1 - window): i2 + window]
        for k in range(j1, j2):
            rescued = use_rescue and span and max(_sim(hyp[k], r) for r in span) >= thr
            labels[k] = 0 if rescued else 1
    return hyp, labels

def encode(tokenizer, source, hyp_words, word_lbls=None, max_len=512):
    hyp_ids, tok_lbls = [], []
    for i, w in enumerate(hyp_words):
        ids = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(" " + w))
        hyp_ids += ids
        if word_lbls is not None:
            tok_lbls += [word_lbls[i]] * len(ids)
    budget = max(0, max_len - len(hyp_ids) - 3)
    src_ids = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(str(source)))[:budget]
    input_ids = ([tokenizer.cls_token_id] + src_ids + [tokenizer.sep_token_id]
                 + hyp_ids + [tokenizer.sep_token_id])[:max_len]
    start = len(src_ids) + 2
    end = min(start + len(hyp_ids), len(input_ids) - 1)
    out = {"input_ids": input_ids, "attention_mask": [1] * len(input_ids), "hyp_span": (start, end)}
    if word_lbls is not None:
        out["labels"] = ([-100] * start + tok_lbls + [-100])[:len(input_ids)]
    return out

class HallucinationDataset(torch.utils.data.Dataset):
    def __init__(self, df, tokenizer, max_len=512):
        self.df, self.tok, self.max_len = df.reset_index(drop=True), tokenizer, max_len
    def __len__(self):
        return len(self.df)
    def __getitem__(self, i):
        r = self.df.iloc[i]
        hyp, lbl = word_labels(r["reference"], r["hypothesis"], r["method"])
        e = encode(self.tok, r["sinhala"], hyp, lbl, self.max_len)
        e.pop("hyp_span")
        return e

def token_metrics(preds, labels):
    m = labels != -100
    y, p = labels[m], preds[m]
    pr, rc, f1, _ = precision_recall_fscore_support(y, p, average="binary", zero_division=0)
    return {"accuracy": accuracy_score(y, p), "precision": pr, "recall": rc, "f1": f1}

# Label sanity check: share of label-1 rows with no positive token, per strategy
_chk = train_df[train_df.label == 1].copy()
_chk["n_pos"] = [sum(word_labels(r.reference, r.hypothesis, r.method)[1]) for r in _chk.itertuples()]
print("Label-1 rows with zero positive tokens, by base strategy:")
print(_chk.groupby(_chk["method"].str.split(" \\+ ").str[0])["n_pos"]
          .apply(lambda s: f"{(s == 0).mean():.1%} of {len(s)}").to_string())

Label-1 rows with zero positive tokens, by base strategy:
method
dependency     0.0% of 138
ner           0.1% of 1145
number         0.0% of 168
semantic      0.0% of 1985
temp          0.2% of 1802

In [5]:
from transformers import (AutoTokenizer, AutoModelForTokenClassification, Trainer,
                          TrainingArguments, DataCollatorForTokenClassification)

def train_and_eval(name, checkpoint, train, val, test, seed, save=True):
    set_seed(seed)
    tok = AutoTokenizer.from_pretrained(checkpoint)
    model = AutoModelForTokenClassification.from_pretrained(checkpoint, num_labels=2)
    run_dir = os.path.join(OUT_DIR, f"run_{name}_s{seed}")
    args = TrainingArguments(
        output_dir=run_dir, learning_rate=LR, per_device_train_batch_size=BATCH,
        per_device_eval_batch_size=32, num_train_epochs=EPOCHS, weight_decay=0.01,
        max_grad_norm=1.0, eval_strategy="epoch", save_strategy="epoch", save_total_limit=1,
        load_best_model_at_end=True, metric_for_best_model="f1", fp16=torch.cuda.is_available(),
        seed=seed, data_seed=seed, report_to="none", logging_steps=100,
    )
    trainer = Trainer(
        model=model, args=args,
        train_dataset=HallucinationDataset(train, tok),
        eval_dataset=HallucinationDataset(val, tok),
        data_collator=DataCollatorForTokenClassification(tok),
        compute_metrics=lambda p: token_metrics(np.argmax(p.predictions, -1), p.label_ids),
    )
    trainer.train()

    res = {"detector": name, "seed": seed}
    pred = trainer.predict(HallucinationDataset(test, tok))
    res.update({f"test_{k}": v for k, v in
                token_metrics(np.argmax(pred.predictions, -1), pred.label_ids).items()})
    base = test["method"].str.split(" \\+ ").str[0]
    for strat in sorted(base.unique()):
        if strat.startswith("ground_truth"):
            continue
        p = trainer.predict(HallucinationDataset(test[base == strat], tok))
        res[f"f1_{strat}"] = token_metrics(np.argmax(p.predictions, -1), p.label_ids)["f1"]

    if save:
        path = os.path.join(MODEL_DIR, f"{name}_s{seed}")
        trainer.save_model(path); tok.save_pretrained(path)
    shutil.rmtree(run_dir, ignore_errors=True)
    model = trainer.model
    del trainer; free_gpu()
    return model, tok, res

def load_detector(name, seed):
    path = os.path.join(MODEL_DIR, f"{name}_s{seed}")
    tok = AutoTokenizer.from_pretrained(path)
    return AutoModelForTokenClassification.from_pretrained(path).to(DEVICE).eval(), tok

In [6]:
if RUN_TRAIN:
    rows = []
    for name, ckpt in DETECTORS.items():
        for seed in SEEDS:
            print(f"\n=== {name}  seed {seed} ===")
            m, t, r = train_and_eval(name, ckpt, train_df, val_df, test_df, seed,
                                     save=(name == PRIMARY))
            print({k: round(v, 4) for k, v in r.items() if isinstance(v, float)})
            rows.append(r); del m; free_gpu()
    table3 = pd.DataFrame(rows)
    table3.to_csv(os.path.join(OUT_DIR, "table3_detector.csv"), index=False)

table3 = pd.read_csv(os.path.join(OUT_DIR, "table3_detector.csv"))
summary = table3.drop(columns="seed").groupby("detector").agg(["mean", "std"]).round(4)
print("TABLE 3 — token-level TEST metrics, mean ± std over seeds")
display(summary.T)

=== mdeberta  seed 42 ===

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of DebertaV2ForTokenClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

{'test_accuracy': 0.9464, 'test_precision': 0.8479, 'test_recall': 0.8357, 'test_f1': 0.8417, 'f1_dependency': 0.8087, 'f1_ner': 0.9194, 'f1_number': 0.9315, 'f1_semantic': 0.9319, 'f1_temp': 0.8302}

=== mdeberta  seed 43 ===

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForTokenClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'test_accuracy': 0.9446, 'test_precision': 0.8296, 'test_recall': 0.8494, 'test_f1': 0.8394, 'f1_dependency': 0.7883, 'f1_ner': 0.9087, 'f1_number': 0.903, 'f1_semantic': 0.9326, 'f1_temp': 0.829}

=== mdeberta  seed 44 ===

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForTokenClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'test_accuracy': 0.9468, 'test_precision': 0.856, 'test_recall': 0.8268, 'test_f1': 0.8412, 'f1_dependency': 0.815, 'f1_ner': 0.9202, 'f1_number': 0.9643, 'f1_semantic': 0.9375, 'f1_temp': 0.8245}

=== xlmr  seed 42 ===

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Some weights of XLMRobertaForTokenClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'test_accuracy': 0.929, 'test_precision': 0.7926, 'test_recall': 0.7928, 'test_f1': 0.7927, 'f1_dependency': 0.7584, 'f1_ner': 0.8577, 'f1_number': 0.8711, 'f1_semantic': 0.8584, 'f1_temp': 0.7903}

=== xlmr  seed 43 ===

Some weights of XLMRobertaForTokenClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'test_accuracy': 0.9303, 'test_precision': 0.8365, 'test_recall': 0.7369, 'test_f1': 0.7835, 'f1_dependency': 0.713, 'f1_ner': 0.8749, 'f1_number': 0.8464, 'f1_semantic': 0.8491, 'f1_temp': 0.7761}

=== xlmr  seed 44 ===

Some weights of XLMRobertaForTokenClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'test_accuracy': 0.9312, 'test_precision': 0.8269, 'test_recall': 0.7567, 'test_f1': 0.7902, 'f1_dependency': 0.7857, 'f1_ner': 0.8479, 'f1_number': 0.8475, 'f1_semantic': 0.8645, 'f1_temp': 0.7847}
TABLE 3 — token-level TEST metrics, mean ± std over seeds

detector             mdeberta    xlmr
test_accuracy  mean    0.9459  0.9302
               std     0.0012  0.0011
test_precision mean    0.8445  0.8187
               std     0.0135  0.0231
test_recall    mean    0.8373  0.7621
               std     0.0114  0.0283
test_f1        mean    0.8408  0.7888
               std     0.0012  0.0047
f1_dependency  mean    0.8040  0.7524
               std     0.0139  0.0367
f1_ner         mean    0.9161  0.8602
               std     0.0064  0.0137
f1_number      mean    0.9329  0.8550
               std     0.0307  0.0139
f1_semantic    mean    0.9340  0.8574
               std     0.0030  0.0078
f1_temp        mean    0.8279  0.7837
               std     0.0030  0.0072

### Detector inference & threshold calibration

`detector_scores` uses the training `encode()` and passes the attention mask (the old benchmark code omitted it on 512-padded inputs, so the model attended to padding). It returns the ratio $R_H$, the max token probability (a single-token aggregator), and per-token probabilities. τ is chosen on validation by sentence-level F1.

In [7]:
from sklearn.metrics import f1_score, roc_auc_score

@torch.no_grad()
def detector_scores(model, tok, sources, hyps, bs=32, token_thr=0.5):
    model.eval().to(DEVICE)
    ratios, maxp, probs = [], [], []
    sources, hyps = list(sources), list(hyps)
    for i in range(0, len(sources), bs):
        items = [encode(tok, s, norm_words(h)) for s, h in zip(sources[i:i + bs], hyps[i:i + bs])]
        L = max(len(x["input_ids"]) for x in items)
        ids = torch.full((len(items), L), tok.pad_token_id)
        am = torch.zeros((len(items), L), dtype=torch.long)
        for b, x in enumerate(items):
            n = len(x["input_ids"]); ids[b, :n] = torch.tensor(x["input_ids"]); am[b, :n] = 1
        p1 = model(input_ids=ids.to(DEVICE), attention_mask=am.to(DEVICE)) \
            .logits.softmax(-1)[..., 1].float().cpu().numpy()
        for b, x in enumerate(items):
            s, e = x["hyp_span"]; p = p1[b, s:e]
            probs.append(p)
            ratios.append(float((p > token_thr).mean()) if len(p) else 0.0)
            maxp.append(float(p.max()) if len(p) else 0.0)
    return np.array(ratios), np.array(maxp), probs

def calibrate_tau(val_ratios, val_labels, grid=np.round(np.arange(0.05, 0.51, 0.05), 2)):
    scores = {t: f1_score(val_labels, (val_ratios > t).astype(int)) for t in grid}
    return max(scores, key=scores.get), scores

TAU = {}
for seed in SEEDS:
    det, dtok = load_detector(PRIMARY, seed)
    vr, _, _ = detector_scores(det, dtok, val_df.sinhala, val_df.hypothesis)
    TAU[seed], sc = calibrate_tau(vr, val_df.label.values)
    print(f"seed {seed}: tau = {TAU[seed]}  (val sentence F1 {sc[TAU[seed]]:.3f})")
    del det; free_gpu()
json.dump({str(k): v for k, v in TAU.items()}, open(os.path.join(OUT_DIR, "tau.json"), "w"))

seed 42: tau = 0.05  (val sentence F1 0.931)
seed 43: tau = 0.05  (val sentence F1 0.917)
seed 44: tau = 0.05  (val sentence F1 0.927)

## 4. Source-Ablation Control

All corruptions are monolingual English edits of the reference, so the detector could be recognising *perturbed English* rather than *unfaithfulness to the source*. Four checks:

| Condition | Change | Question |
|---|---|---|
| Original | — | baseline |
| Shuffled | source replaced by a different, length-matched test source; gold labels unchanged | does the model read the source at test time? |
| Removed | source set to empty | same, more severe |
| Hypothesis-only | model retrained with the source blanked everywhere | is the task solvable without the source? |
| Mismatch test | *faithful* hypotheses paired with a wrong source | does it flag fully detached pairs? (a hypothesis-only detector will not) |

In [8]:
def shuffle_sources(df, seed=SPLIT_SEED, shift=1):
    """Length-matched derangement over unique sources."""
    rng = np.random.default_rng(seed)
    uniq = df["sinhala"].drop_duplicates().tolist()
    rng.shuffle(uniq)
    order = sorted(uniq, key=len)
    mapping = {order[i]: order[(i + shift) % len(order)] for i in range(len(order))}
    out = df.copy()
    out["sinhala"] = out["sinhala"].map(mapping)
    assert (out["sinhala"].values != df["sinhala"].values).all()
    return out

@torch.no_grad()
def eval_condition(model, tok, df, tau, bs=32):
    """Token metrics vs the ORIGINAL gold labels + sentence-level AUROC and flag rate."""
    model.eval().to(DEVICE)
    all_p, all_y, ratios, maxp = [], [], [], []
    rows = list(df.itertuples(index=False))
    for i in range(0, len(rows), bs):
        items = []
        for r in rows[i:i + bs]:
            hyp, lbl = word_labels(r.reference, r.hypothesis, r.method)
            items.append(encode(tok, r.sinhala, hyp, lbl))
        L = max(len(x["input_ids"]) for x in items)
        ids = torch.full((len(items), L), tok.pad_token_id)
        am = torch.zeros((len(items), L), dtype=torch.long)
        for b, x in enumerate(items):
            n = len(x["input_ids"]); ids[b, :n] = torch.tensor(x["input_ids"]); am[b, :n] = 1
        p1 = model(input_ids=ids.to(DEVICE), attention_mask=am.to(DEVICE)) \
            .logits.softmax(-1)[..., 1].float().cpu().numpy()
        for b, x in enumerate(items):
            s, e = x["hyp_span"]
            pr, lab = p1[b, s:e], np.array(x["labels"][s:e])
            all_p.append(pr); all_y.append(lab)
            ratios.append(float((pr > 0.5).mean()) if len(pr) else 0.0)
            maxp.append(float(pr.max()) if len(pr) else 0.0)
    tm = token_metrics((np.concatenate(all_p) > 0.5).astype(int), np.concatenate(all_y))
    ratios, maxp, y = np.array(ratios), np.array(maxp), df["label"].values
    out = {**{f"tok_{k}": v for k, v in tm.items()},
           "auroc_RH": roc_auc_score(y, ratios) if len(set(y)) > 1 else np.nan,
           "auroc_maxp": roc_auc_score(y, maxp) if len(set(y)) > 1 else np.nan,
           "flag_rate_%": (ratios > tau).mean() * 100}
    return out, ratios

def run_ablation(model, tok, tau, seed, tag):
    rows = []
    conds = {"original": test_df, "shuffled": shuffle_sources(test_df, seed),
             "removed": test_df.assign(sinhala="")}
    for cname, d in conds.items():
        r, _ = eval_condition(model, tok, d, tau)
        rows.append({"model": tag, "seed": seed, "condition": cname, **r})
    gt = test_df[test_df.label == 0]
    _, r_m = eval_condition(model, tok, gt, tau)
    _, r_x = eval_condition(model, tok, shuffle_sources(gt, seed), tau)
    rows.append({"model": tag, "seed": seed, "condition": "mismatch_test",
                 "flag_%_matched_faithful": (r_m > tau).mean() * 100,
                 "flag_%_mismatched_faithful": (r_x > tau).mean() * 100,
                 "mean_RH_matched": r_m.mean(), "mean_RH_mismatched": r_x.mean()})
    return rows

In [9]:
abl_path = os.path.join(OUT_DIR, "table_source_ablation.csv")
if RUN_ABLATION:
    abl = []
    for seed in SEEDS:
        det, dtok = load_detector(PRIMARY, seed)
        abl += run_ablation(det, dtok, TAU[seed], seed, "full")
        del det; free_gpu()

    if RUN_HYP_ONLY:
        blank = lambda d: d.assign(sinhala="")
        for seed in SEEDS:
            print(f"\n=== hypothesis-only  seed {seed} ===")
            m, t, r = train_and_eval("hyponly", DETECTORS[PRIMARY], blank(train_df),
                                     blank(val_df), blank(test_df), seed, save=False)
            vr, _, _ = detector_scores(m, t, [""] * len(val_df), val_df.hypothesis)
            tau_h, _ = calibrate_tau(vr, val_df.label.values)
            res, _ = eval_condition(m, t, blank(test_df), tau_h)
            abl.append({"model": "hypothesis_only", "seed": seed, "condition": "removed(train+test)", **res})
            del m; free_gpu()
    pd.DataFrame(abl).to_csv(abl_path, index=False)

abl = pd.read_csv(abl_path)
metric_cols = ["tok_f1", "auroc_RH", "auroc_maxp", "flag_rate_%",
               "flag_%_matched_faithful", "flag_%_mismatched_faithful"]
print("SOURCE-ABLATION CONTROL — mean ± std over seeds")
display(abl.groupby(["model", "condition"])[[c for c in metric_cols if c in abl]]
           .agg(["mean", "std"]).round(3))

=== hypothesis-only  seed 42 ===

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForTokenClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== hypothesis-only  seed 43 ===

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForTokenClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=== hypothesis-only  seed 44 ===

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForTokenClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

SOURCE-ABLATION CONTROL — mean ± std over seeds

                                    tok_f1        auroc_RH        auroc_maxp  \
                                      mean    std     mean    std       mean
model           condition
full            mismatch_test          NaN    NaN      NaN    NaN        NaN
                original             0.841  0.002    0.970  0.002      0.992
                removed              0.295  0.004    0.507  0.028      0.655
                shuffled             0.314  0.003    0.540  0.007      0.627
hypothesis_only removed(train+test)  0.622  0.008    0.850  0.010      0.906

                                           flag_rate_%         \
                                       std        mean    std
model           condition
full            mismatch_test          NaN         NaN    NaN
                original             0.000      46.249  0.602
                removed              0.026     100.000  0.000
                shuffled             0.030     100.000  0.000
hypothesis_only removed(train+test)  0.013      44.724  3.690

                                    flag_%_matched_faithful         \
                                                       mean    std
model           condition
full            mismatch_test                         3.242  0.619
                original                                NaN    NaN
                removed                                 NaN    NaN
                shuffled                                NaN    NaN
hypothesis_only removed(train+test)                     NaN    NaN

                                    flag_%_mismatched_faithful
                                                          mean  std
model           condition
full            mismatch_test                            100.0  0.0
                original                                   NaN  NaN
                removed                                    NaN  NaN
                shuffled                                   NaN  NaN
hypothesis_only removed(train+test)                        NaN  NaN

### 4b. Remedy: source-mismatch augmentation (optional)

Enable `RUN_AUGMENT` if the control shows the detector barely uses the source. Faithful training hypotheses paired with a wrong source are added as all-1 rows (20% of faithful train rows; validation and test untouched), so these can only be classified correctly by reading the source. The ablation is then re-run on the augmented model.

In [10]:
def add_mismatch_negatives(df, frac=0.2, seed=SPLIT_SEED):
    gt = df[df.label == 0].sample(frac=frac, random_state=seed)
    neg = shuffle_sources(gt, seed).assign(label=1, method="source_mismatch")
    return pd.concat([df, neg]).sample(frac=1, random_state=seed).reset_index(drop=True)

if RUN_AUGMENT:
    aug_rows, abl_aug = [], []
    for seed in SEEDS:
        print(f"\n=== mDeBERTa + mismatch augmentation  seed {seed} ===")
        m, t, r = train_and_eval("mdeberta_aug", DETECTORS[PRIMARY],
                                 add_mismatch_negatives(train_df, seed=seed), val_df, test_df, seed)
        aug_rows.append(r)
        vr, _, _ = detector_scores(m, t, val_df.sinhala, val_df.hypothesis)
        tau_a, _ = calibrate_tau(vr, val_df.label.values)
        abl_aug += run_ablation(m, t, tau_a, seed, "full+mismatch_aug")
        del m; free_gpu()
    pd.DataFrame(aug_rows).to_csv(os.path.join(OUT_DIR, "table3_detector_aug.csv"), index=False)
    abl_all = pd.concat([pd.read_csv(abl_path), pd.DataFrame(abl_aug)])
    abl_all.to_csv(abl_path, index=False)
    display(abl_all.groupby(["model", "condition"])[[c for c in metric_cols if c in abl_all]]
                   .agg(["mean", "std"]).round(3))

## 5. Ensemble Evaluation on the Synthetic Split

The ensemble is evaluated where the gold label refers to the text being scored: the stored synthetic hypothesis. For each val/test row we compute $R_H$ (primary detector), the sequence log-probability of **that hypothesis** under NLLB-200-1.3B via teacher forcing, and LaBSE similarity to the source. Weights and threshold are tuned on validation (grid over the simplex, step 0.1) and reported on test, alongside the five named configurations (each with its own val-tuned threshold) and per-signal AUROC. The log-prob normaliser is fitted on validation and applied to test.

*(The previous ablation compared the synthetic label with scores computed on a fresh NMT translation, and silently dropped LaBSE because the `labse_risk_*` column was never created.)*

In [11]:
from transformers import AutoModel, AutoModelForSeq2SeqLM

tok_labse = AutoTokenizer.from_pretrained("sentence-transformers/LaBSE")
mdl_labse = AutoModel.from_pretrained("sentence-transformers/LaBSE").to(DEVICE).eval()

@torch.no_grad()
def labse_sim(a, b, bs=32):
    def emb(texts):
        vs = []
        texts = [str(t) for t in texts]
        for i in range(0, len(texts), bs):
            e = tok_labse(texts[i:i + bs], padding=True, truncation=True,
                          max_length=512, return_tensors="pt").to(DEVICE)
            h = mdl_labse(**e)[0]
            m = e["attention_mask"].unsqueeze(-1).float()
            vs.append(torch.nn.functional.normalize((h * m).sum(1) / m.sum(1).clamp(min=1e-9), dim=1).cpu())
        return torch.cat(vs)
    return (emb(a) * emb(b)).sum(1).numpy()

@torch.no_grad()
def forced_logprob_nllb(model, tok, sources, hyps, bs=16):
    """Summed log-prob of a GIVEN hypothesis under NLLB (teacher forcing)."""
    tok.src_lang, tok.tgt_lang = "sin_Sinh", "eng_Latn"
    sources, hyps, out = list(sources), list(hyps), []
    for i in tqdm(range(0, len(sources), bs), desc="Forced log-prob"):
        enc = tok(sources[i:i + bs], text_target=hyps[i:i + bs], return_tensors="pt",
                  padding=True, truncation=True, max_length=256).to(DEVICE)
        labels = enc.pop("labels")
        labels[labels == tok.pad_token_id] = -100
        logits = model(**enc, labels=labels).logits
        lp = logits.log_softmax(-1).gather(-1, labels.clamp(min=0).unsqueeze(-1)).squeeze(-1)
        out += (lp * (labels != -100)).sum(1).cpu().tolist()
    return np.array(out)

tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/804 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.88G [00:00<?, ?B/s]

In [12]:
from sklearn.metrics import precision_recall_fscore_support

def fit_lp_norm(lp):
    c = np.minimum(lp, 0)
    lo, hi = np.nanmin(c), np.nanmax(c)
    return lambda x: np.clip((np.minimum(x, 0) - hi) / (lo - hi + 1e-9), 0, 1)

def ensemble_score(df, w, lp_norm):
    return w[0] * df["r"] + w[1] * lp_norm(df["lp"].values) + w[2] * (1 - df["rho"])

NAMED_W = {"Det-Mild": (.5, .3, .2), "Det-Heavy": (.7, .2, .1), "LP-Heavy": (.2, .6, .2),
           "Sem-Heavy": (.2, .2, .6), "Uniform": (1/3, 1/3, 1/3)}
THR_GRID = np.round(np.arange(0.20, 0.71, 0.05), 2)

def evaluate_ensemble(val, test):
    lp_norm = fit_lp_norm(val["lp"].values)
    def prf(df, w, t):
        y, p = df["label"], (ensemble_score(df, w, lp_norm) >= t).astype(int)
        pr, rc, f1, _ = precision_recall_fscore_support(y, p, average="binary", zero_division=0)
        return pr, rc, f1, p.mean() * 100
    best = (-1, None, None)
    grid = [(round(a, 1), round(b, 1), round(1 - a - b, 1))
            for a in np.arange(0, 1.01, 0.1) for b in np.arange(0, 1.01 - a + 1e-9, 0.1)]
    for w in grid:
        for t in THR_GRID:
            f1 = prf(val, w, t)[2]
            if f1 > best[0]:
                best = (f1, w, t)
    rows = []
    for name, w in {**NAMED_W, "Val-tuned": best[1]}.items():
        t = best[2] if name == "Val-tuned" else max(THR_GRID, key=lambda t: prf(val, w, t)[2])
        pr, rc, f1, fr = prf(test, w, t)
        rows.append({"config": name, "w_det/w_lp/w_sem": "/".join(f"{x:.2f}" for x in w), "thr": t,
                     "precision": pr, "recall": rc, "f1": f1, "flag_%": fr,
                     "auroc": roc_auc_score(test["label"], ensemble_score(test, w, lp_norm))})
    single = {"R_H": roc_auc_score(test["label"], test["r"]),
              "-logprob": roc_auc_score(test["label"], -test["lp"]),
              "1-LaBSE": roc_auc_score(test["label"], 1 - test["rho"])}
    return pd.DataFrame(rows), single

if RUN_ENSEMBLE:
    det, dtok = load_detector(PRIMARY, PRIMARY_SEED)
    sig = {}
    for name, d in [("val", val_df), ("test", test_df)]:
        r, mp, _ = detector_scores(det, dtok, d.sinhala, d.hypothesis)
        sig[name] = d.assign(r=r, maxp=mp, rho=labse_sim(d.sinhala, d.hypothesis))
    del det; free_gpu()

    tok_nllb = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-1.3B")
    mdl_nllb = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-1.3B").to(DEVICE).eval()
    for name in sig:
        sig[name]["lp"] = forced_logprob_nllb(mdl_nllb, tok_nllb, sig[name].sinhala, sig[name].hypothesis)
    del mdl_nllb; free_gpu()

    for name in sig:
        sig[name].to_csv(os.path.join(OUT_DIR, f"signals_{name}.csv"), index=False)
    table5, single_auc = evaluate_ensemble(sig["val"], sig["test"])
    table5.to_csv(os.path.join(OUT_DIR, "table5_ensemble.csv"), index=False)
    print("Single-signal test AUROC:", {k: round(v, 3) for k, v in single_auc.items()})
    display(table5.round(3))

    # Weights used for the NMT benchmark: keep the paper's Det-Mild unless you switch to Val-tuned
    CHOSEN = "Det-Mild"
    row = table5.set_index("config").loc[CHOSEN]
    CHOSEN_W = tuple(float(x) for x in row["w_det/w_lp/w_sem"].split("/"))
    CHOSEN_THR = float(row["thr"])
    json.dump({"config": CHOSEN, "w": CHOSEN_W, "thr": CHOSEN_THR},
              open(os.path.join(OUT_DIR, "chosen_ensemble.json"), "w"))
    print("Benchmark ensemble:", CHOSEN, CHOSEN_W, "thr", CHOSEN_THR)

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/808 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/5.48G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/5.48G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

Forced log-prob:   0%|          | 0/94 [00:00<?, ?it/s]

Forced log-prob:   0%|          | 0/189 [00:00<?, ?it/s]

Single-signal test AUROC: {'R_H': 0.972, '-logprob': 0.88, '1-LaBSE': 0.882}

      config w_det/w_lp/w_sem  thr  precision  recall     f1  flag_%  auroc
0   Det-Mild   0.50/0.30/0.20  0.2      0.973   0.428  0.595  22.108  0.971
1  Det-Heavy   0.70/0.20/0.10  0.2      0.975   0.420  0.587  21.611  0.977
2   LP-Heavy   0.20/0.60/0.20  0.2      0.955   0.447  0.609  23.500  0.938
3  Sem-Heavy   0.20/0.20/0.60  0.2      0.974   0.470  0.634  24.263  0.944
4    Uniform   0.33/0.33/0.33  0.2      0.970   0.441  0.607  22.870  0.961
5  Val-tuned   0.10/0.20/0.70  0.2      0.972   0.481  0.643  24.859  0.927

Benchmark ensemble: Det-Mild (0.5, 0.3, 0.2) thr 0.2

## 6. NMT Benchmark

Eight systems translate the **unique** test sources (duplicate sources from the synthetic design are removed). Generation: beam 4, `max_new_tokens=256`. Sequence log-probability is recomputed by teacher forcing on the generated ids **without** the decoder-start token (the model re-prepends it; the old code scored it as a prediction). Failed translations are excluded from every signal and counted. OPUS-MT mul-en has a single target language, so no `>>en<<` tag is prepended.

Signals per model: $R_H$ (primary detector, τ from validation), log-prob (fires below the model's own 30th percentile), LaBSE (fires below 0.80), and the weighted ensemble (per-model min-max log-prob normalisation, weights/threshold from Section 5).

In [13]:
from transformers import (M2M100ForConditionalGeneration, MarianMTModel, MarianTokenizer)

MODELS = {
    "nllb_600m":   ("facebook/nllb-200-distilled-600M",        "nllb"),
    "nllb_1.3b":   ("facebook/nllb-200-distilled-1.3B",        "nllb"),
    "m2m_418m":    ("facebook/m2m100_418M",                    "m2m"),
    "m2m_1.2b":    ("facebook/m2m100_1.2B",                    "m2m"),
    "mbart50_m2m": ("facebook/mbart-large-50-many-to-many-mmt","mbart"),
    "mbart50_m2o": ("facebook/mbart-large-50-many-to-one-mmt", "mbart"),
    "mt5_sin":     ("thilina/mt5-sinhalese-english",           "mt5"),     # community fine-tune
    "opus_mul_en": ("Helsinki-NLP/opus-mt-mul-en",             "marian"),
}
FAMILY = {  # family: (src_lang, forced-BOS getter)
    "nllb":   ("sin_Sinh", lambda t: t.convert_tokens_to_ids("eng_Latn")),
    "mbart":  ("si_LK",    lambda t: t.lang_code_to_id["en_XX"]),
    "m2m":    ("si",       lambda t: t.get_lang_id("en")),
    "mt5":    (None, None),
    "marian": (None, None),
}

def load_nmt(path, family):
    if family == "marian":
        return MarianTokenizer.from_pretrained(path), MarianMTModel.from_pretrained(path).to(DEVICE).eval()
    if family == "m2m":
        return AutoTokenizer.from_pretrained(path), M2M100ForConditionalGeneration.from_pretrained(path).to(DEVICE).eval()
    return AutoTokenizer.from_pretrained(path), AutoModelForSeq2SeqLM.from_pretrained(path).to(DEVICE).eval()

@torch.no_grad()
def translate_batch(model, tok, family, texts, bs=16, num_beams=4, max_new_tokens=256):
    src_lang, bos_fn = FAMILY[family]
    if src_lang:
        tok.src_lang = src_lang
    hyps, lps, errs = [], [], []
    for i in tqdm(range(0, len(texts), bs), desc="Translating"):
        batch = list(texts[i:i + bs])
        try:
            enc = tok(batch, return_tensors="pt", padding=True, truncation=True, max_length=512).to(DEVICE)
            kw = dict(num_beams=num_beams, max_new_tokens=max_new_tokens)
            if bos_fn:
                kw["forced_bos_token_id"] = bos_fn(tok)
            gen = model.generate(**enc, **kw)
            labels = gen[:, 1:].clone()
            labels[labels == tok.pad_token_id] = -100
            logits = model(**enc, labels=labels).logits
            lp = logits.log_softmax(-1).gather(-1, labels.clamp(min=0).unsqueeze(-1)).squeeze(-1)
            hyps += tok.batch_decode(gen, skip_special_tokens=True)
            lps += (lp * (labels != -100)).sum(1).cpu().tolist()
            errs += [False] * len(batch)
        except Exception as e:
            print("  batch failed:", repr(e)[:200])
            hyps += [""] * len(batch); lps += [np.nan] * len(batch); errs += [True] * len(batch)
    hyps = [h.strip() for h in hyps]
    errs = [e or (h == "") for e, h in zip(errs, hyps)]
    return hyps, np.array(lps), np.array(errs)

In [14]:
LP_PCT, LABSE_THR = 30.0, 0.80
bench_path = os.path.join(OUT_DIR, "benchmark_outputs.csv")

if RUN_BENCHMARK:
    cfg = json.load(open(os.path.join(OUT_DIR, "chosen_ensemble.json")))
    W, ENS_THR, tau = cfg["w"], cfg["thr"], TAU[PRIMARY_SEED]
    bench = test_df.drop_duplicates("sinhala")[["sinhala", "reference"]].reset_index(drop=True)
    print(f"Benchmarking {len(bench)} unique test sources; tau={tau}, ensemble {cfg['config']} thr={ENS_THR}")
    det, dtok = load_detector(PRIMARY, PRIMARY_SEED)
    log = []
    for m, (path, fam) in MODELS.items():
        print(f"\n=== {m} ===")
        tok_mt, mdl_mt = load_nmt(path, fam)
        hyps, lps, errs = translate_batch(mdl_mt, tok_mt, fam, bench.sinhala.tolist())
        del mdl_mt, tok_mt; free_gpu()
        ok = ~errs
        bench[f"hyp_{m}"], bench[f"lp_{m}"], bench[f"err_{m}"] = hyps, lps, errs
        risk, maxp, labse = (np.full(len(bench), np.nan) for _ in range(3))
        r_ok, mp_ok, _ = detector_scores(det, dtok, bench.sinhala[ok], bench[f"hyp_{m}"][ok])
        risk[ok], maxp[ok] = r_ok, mp_ok
        labse[ok] = labse_sim(bench.sinhala[ok], bench[f"hyp_{m}"][ok])
        bench[f"risk_{m}"], bench[f"maxp_{m}"], bench[f"labse_{m}"] = risk, maxp, labse

        lp_thr = np.percentile(lps[ok], LP_PCT)
        f_det = ok & (risk > tau)
        f_lp  = ok & (lps < lp_thr)
        f_sem = ok & (labse < LABSE_THR)
        lp_norm = fit_lp_norm(lps[ok])
        ens = np.full(len(bench), np.nan)
        ens[ok] = W[0] * risk[ok] + W[1] * lp_norm(lps[ok]) + W[2] * (1 - labse[ok])
        bench[f"ens_{m}"] = ens
        bench[f"flag_det_{m}"], bench[f"flag_lp_{m}"], bench[f"flag_sem_{m}"] = f_det, f_lp, f_sem
        bench[f"flag_ens_{m}"] = ok & (ens >= ENS_THR)

        log.append({
            "Model": m, "Family": fam, "Errors": int(errs.sum()), "Scored": int(ok.sum()),
            "Avg LogProb": float(np.mean(lps[ok])), "LP thresh": float(lp_thr),
            "All 3": int((f_det & f_lp & f_sem).sum()), "Det+LP": int((f_det & f_lp & ~f_sem).sum()),
            "Det+LaBSE": int((f_det & ~f_lp & f_sem).sum()), "LP+LaBSE": int((~f_det & f_lp & f_sem).sum()),
            "Det only": int((f_det & ~f_lp & ~f_sem).sum()), "LP only": int((~f_det & f_lp & ~f_sem).sum()),
            "LaBSE only": int((~f_det & ~f_lp & f_sem).sum()),
            "None": int((ok & ~f_det & ~f_lp & ~f_sem).sum()),
            "Ensemble flags": int(bench[f"flag_ens_{m}"].sum()),
        })
        print(log[-1])
    del det; free_gpu()
    bench.to_csv(bench_path, index=False)
    pd.DataFrame(log).to_csv(os.path.join(OUT_DIR, "table4_partitions.csv"), index=False)

table4 = pd.read_csv(os.path.join(OUT_DIR, "table4_partitions.csv"))
print("TABLE 4 — signal partitions per model (partition columns sum to 'Scored')")
display(table4)

Benchmarking 1485 unique test sources; tau=0.05, ensemble Det-Mild thr=0.2

=== nllb_600m ===

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

{'Model': 'nllb_600m', 'Family': 'nllb', 'Errors': 0, 'Scored': 1485, 'Avg LogProb': -10.166655434502495, 'LP thresh': -11.264658164978027, 'All 3': 4, 'Det+LP': 10, 'Det+LaBSE': 2, 'LP+LaBSE': 7, 'Det only': 20, 'LP only': 425, 'LaBSE only': 12, 'None': 1005, 'Ensemble flags': 17}

=== nllb_1.3b ===

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

{'Model': 'nllb_1.3b', 'Family': 'nllb', 'Errors': 0, 'Scored': 1485, 'Avg LogProb': -9.44683927373854, 'LP thresh': -10.463102340698242, 'All 3': 6, 'Det+LP': 14, 'Det+LaBSE': 7, 'LP+LaBSE': 12, 'Det only': 24, 'LP only': 414, 'LaBSE only': 22, 'None': 986, 'Ensemble flags': 31}

=== m2m_418m ===

tokenizer_config.json:   0%|          | 0.00/298 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/233 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

{'Model': 'm2m_418m', 'Family': 'm2m', 'Errors': 0, 'Scored': 1485, 'Avg LogProb': -16.03652718380244, 'LP thresh': -17.595762634277342, 'All 3': 38, 'Det+LP': 80, 'Det+LaBSE': 21, 'LP+LaBSE': 34, 'Det only': 64, 'LP only': 294, 'LaBSE only': 55, 'None': 899, 'Ensemble flags': 40}

=== m2m_1.2b ===

tokenizer_config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/909 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/233 [00:00<?, ?B/s]

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

{'Model': 'm2m_1.2b', 'Family': 'm2m', 'Errors': 0, 'Scored': 1485, 'Avg LogProb': -14.53522141324952, 'LP thresh': -15.558389472961426, 'All 3': 22, 'Det+LP': 35, 'Det+LaBSE': 12, 'LP+LaBSE': 40, 'Det only': 33, 'LP only': 349, 'LaBSE only': 43, 'None': 951, 'Ensemble flags': 24}

=== mbart50_m2m ===

tokenizer_config.json:   0%|          | 0.00/529 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/649 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/261 [00:00<?, ?B/s]

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

{'Model': 'mbart50_m2m', 'Family': 'mbart', 'Errors': 0, 'Scored': 1485, 'Avg LogProb': -8.210526433296074, 'LP thresh': -9.250321197509766, 'All 3': 13, 'Det+LP': 48, 'Det+LaBSE': 13, 'LP+LaBSE': 9, 'Det only': 34, 'LP only': 376, 'LaBSE only': 31, 'None': 961, 'Ensemble flags': 58}

=== mbart50_m2o ===

tokenizer_config.json:   0%|          | 0.00/461 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/649 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/268 [00:00<?, ?B/s]

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

{'Model': 'mbart50_m2o', 'Family': 'mbart', 'Errors': 0, 'Scored': 1485, 'Avg LogProb': -7.969758648342556, 'LP thresh': -9.059824562072754, 'All 3': 5, 'Det+LP': 38, 'Det+LaBSE': 10, 'LP+LaBSE': 9, 'Det only': 25, 'LP only': 394, 'LaBSE only': 26, 'None': 978, 'Ensemble flags': 8}

=== mt5_sin ===

tokenizer_config.json:   0%|          | 0.00/393 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/644 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

  batch failed: OutOfMemoryError('CUDA out of memory. Tried to allocate 3.82 GiB. GPU 0 has a total capacity of 14.56 GiB of which 1.60 GiB is free. Including non-PyTorch memory, this process has 12.96 GiB memory in
  batch failed: OutOfMemoryError('CUDA out of memory. Tried to allocate 3.82 GiB. GPU 0 has a total capacity of 14.56 GiB of which 1.60 GiB is free. Including non-PyTorch memory, this process has 12.96 GiB memory in
  batch failed: OutOfMemoryError('CUDA out of memory. Tried to allocate 3.82 GiB. GPU 0 has a total capacity of 14.56 GiB of which 1.60 GiB is free. Including non-PyTorch memory, this process has 12.96 GiB memory in
{'Model': 'mt5_sin', 'Family': 'mt5', 'Errors': 48, 'Scored': 1437, 'Avg LogProb': -77.40146354975266, 'LP thresh': -85.73018951416016, 'All 3': 30, 'Det+LP': 26, 'Det+LaBSE': 103, 'LP+LaBSE': 41, 'Det only': 96, 'LP only': 334, 'LaBSE only': 60, 'None': 747, 'Ensemble flags': 108}

=== opus_mul_en ===

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/707k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/791k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/310M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

Translating:   0%|          | 0/93 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/310M [00:00<?, ?B/s]

{'Model': 'opus_mul_en', 'Family': 'marian', 'Errors': 0, 'Scored': 1485, 'Avg LogProb': -423.1224383370242, 'LP thresh': -491.70563354492185, 'All 3': 88, 'Det+LP': 57, 'Det+LaBSE': 123, 'LP+LaBSE': 23, 'Det only': 94, 'LP only': 278, 'LaBSE only': 92, 'None': 730, 'Ensemble flags': 184}
TABLE 4 — signal partitions per model (partition columns sum to 'Scored')

,Model,Family,Errors,Scored,Avg LogProb,LP thresh,All 3,Det+LP,Det+LaBSE,LP+LaBSE,Det only,LP only,LaBSE only,None,Ensemble flags
0,nllb_600m,nllb,0,1485,-10.166655,-11.264658,4,10,2,7,20,425,12,1005,17
1,nllb_1.3b,nllb,0,1485,-9.446839,-10.463102,6,14,7,12,24,414,22,986,31
2,m2m_418m,m2m,0,1485,-16.036527,-17.595763,38,80,21,34,64,294,55,899,40
3,m2m_1.2b,m2m,0,1485,-14.535221,-15.558389,22,35,12,40,33,349,43,951,24
4,mbart50_m2m,mbart,0,1485,-8.210526,-9.250321,13,48,13,9,34,376,31,961,58
5,mbart50_m2o,mbart,0,1485,-7.969759,-9.059825,5,38,10,9,25,394,26,978,8
6,mt5_sin,mt5,48,1437,-77.401464,-85.730190,30,26,103,41,96,334,60,747,108
7,opus_mul_en,marian,0,1485,-423.122438,-491.705634,88,57,123,23,94,278,92,730,184

## 7. Signal Independence & Threshold Sensitivity

Spearman ρ between log-probability and $R_H$ per model (scored rows only), and flag counts across τ.

In [15]:
from scipy.stats import spearmanr
bench = pd.read_csv(bench_path)
tau = TAU[PRIMARY_SEED]
rows = []
for m in MODELS:
    ok = ~bench[f"err_{m}"].astype(bool)
    rho, p = spearmanr(bench.loc[ok, f"lp_{m}"], bench.loc[ok, f"risk_{m}"])
    sweep = {f"tau={t}": int((bench.loc[ok, f"risk_{m}"] > t).sum())
             for t in [0.10, 0.15, 0.20, 0.25, 0.30, 0.35]}
    rows.append({"model": m, "spearman_rho": rho, "p_value": p, **sweep})
display(pd.DataFrame(rows).round(4))

,model,spearman_rho,p_value,tau=0.1,tau=0.15,tau=0.2,tau=0.25,tau=0.3,tau=0.35
0,nllb_600m,-0.0867,0.0008,22,15,10,7,6,5
1,nllb_1.3b,-0.0819,0.0016,32,23,18,13,11,11
2,m2m_418m,-0.3058,0.0000,109,68,38,26,18,13
3,m2m_1.2b,-0.2201,0.0000,60,41,28,22,15,12
4,mbart50_m2m,-0.2482,0.0000,52,31,18,11,8,7
5,mbart50_m2o,-0.1756,0.0000,42,23,10,6,6,6
6,mt5_sin,0.1516,0.0000,179,139,115,102,89,79
7,opus_mul_en,-0.1791,0.0000,262,219,188,168,154,140

In [17]:
bench = pd.read_csv(bench_path)
m = "mt5_sin"; path, fam = MODELS[m]
idx = np.where(bench[f"err_{m}"].astype(bool).values)[0]
print(len(idx), "failed rows")
free_gpu()
tok_mt, mdl_mt = load_nmt(path, fam)
h, lp, e = translate_batch(mdl_mt, tok_mt, fam, bench.sinhala.iloc[idx].tolist(), bs=2)
del mdl_mt, tok_mt; free_gpu()
bench.loc[idx, f"hyp_{m}"], bench.loc[idx, f"lp_{m}"], bench.loc[idx, f"err_{m}"] = h, lp, e
ok_new = idx[~e]
det, dtok = load_detector(PRIMARY, PRIMARY_SEED)
r, mp, _ = detector_scores(det, dtok, bench.sinhala.iloc[ok_new], bench[f"hyp_{m}"].iloc[ok_new])
bench.loc[ok_new, f"risk_{m}"], bench.loc[ok_new, f"maxp_{m}"] = r, mp
bench.loc[ok_new, f"labse_{m}"] = labse_sim(bench.sinhala.iloc[ok_new], bench[f"hyp_{m}"].iloc[ok_new])
del det; free_gpu()
bench.to_csv(bench_path, index=False)
print("still failing:", int(e.sum()))

48 failed rows

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Translating:   0%|          | 0/24 [00:00<?, ?it/s]

still failing: 0

In [25]:
bench = pd.read_csv(bench_path)
sig_val  = pd.read_csv(os.path.join(OUT_DIR, "signals_val.csv"))
sig_test = pd.read_csv(os.path.join(OUT_DIR, "signals_test.csv"))

# 1. tau below 0.05 (primary seed)
tau_grid = np.round(np.r_[0.0, 0.01, 0.02, 0.03, 0.04, np.arange(0.05, 0.51, 0.05)], 2)
tau_best, tau_sc = calibrate_tau(sig_val.r.values, sig_val.label.values, grid=tau_grid)
print("val sentence F1 by tau:", {t: round(s, 4) for t, s in tau_sc.items()})
print("best tau:", tau_best, "| current:", TAU[PRIMARY_SEED])

# 2. Table 5 with a lower threshold grid + detector-only baseline
THR_GRID = np.round(np.r_[np.arange(0.0, 0.10, 0.01), np.arange(0.10, 0.71, 0.05)], 2)
NAMED_W = {"Detector only": (1.0, 0.0, 0.0), "Det-Mild": (.5, .3, .2), "Det-Heavy": (.7, .2, .1),
           "LP-Heavy": (.2, .6, .2), "Sem-Heavy": (.2, .2, .6), "Uniform": (1/3, 1/3, 1/3)}
table5, single_auc = evaluate_ensemble(sig_val, sig_test)
table5.to_csv(os.path.join(OUT_DIR, "table5_ensemble.csv"), index=False)
print("Single-signal test AUROC:", {k: round(v, 3) for k, v in single_auc.items()})
display(table5.round(3))
if (table5.thr == THR_GRID.min()).any():
    print("WARNING: a threshold is still at the grid minimum")

# 3. Recompute Table 4 + Spearman from saved benchmark signals
row = table5.set_index("config").loc["Det-Mild"]
W = tuple(float(x) for x in row["w_det/w_lp/w_sem"].split("/")); ENS_THR = float(row["thr"])
tau = TAU[PRIMARY_SEED]
json.dump({"config": "Det-Mild", "w": W, "thr": ENS_THR, "tau": tau},
          open(os.path.join(OUT_DIR, "chosen_ensemble.json"), "w"))
log, spear = [], []
for m, (path, fam) in MODELS.items():
    ok = ~bench[f"err_{m}"].astype(bool).values
    lps, risk, labse = (bench[f"{c}_{m}"].values for c in ("lp", "risk", "labse"))
    words = bench[f"hyp_{m}"].astype(str).str.split().str.len().values
    lp_thr = np.percentile(lps[ok], LP_PCT)
    f_det, f_lp, f_sem = ok & (risk > tau), ok & (lps < lp_thr), ok & (labse < LABSE_THR)
    lp_norm = fit_lp_norm(lps[ok])
    ens = np.full(len(bench), np.nan)
    ens[ok] = W[0] * risk[ok] + W[1] * lp_norm(lps[ok]) + W[2] * (1 - labse[ok])
    bench[f"ens_{m}"] = ens
    bench[f"flag_det_{m}"], bench[f"flag_lp_{m}"], bench[f"flag_sem_{m}"] = f_det, f_lp, f_sem
    bench[f"flag_ens_{m}"] = ok & (ens >= ENS_THR)
    log.append({"Model": m, "Family": fam, "Errors": int((~ok).sum()), "Scored": int(ok.sum()),
        "Avg LogProb": lps[ok].mean(), "LogProb/word": (lps[ok] / np.maximum(words[ok], 1)).mean(),
        "Avg words": words[ok].mean(), "% >=150 words": 100 * (words[ok] >= 150).mean(),
        "All 3": int((f_det & f_lp & f_sem).sum()), "Det+LP": int((f_det & f_lp & ~f_sem).sum()),
        "Det+LaBSE": int((f_det & ~f_lp & f_sem).sum()), "LP+LaBSE": int((~f_det & f_lp & f_sem).sum()),
        "Det only": int((f_det & ~f_lp & ~f_sem).sum()), "LP only": int((~f_det & f_lp & ~f_sem).sum()),
        "LaBSE only": int((~f_det & ~f_lp & f_sem).sum()), "None": int((ok & ~f_det & ~f_lp & ~f_sem).sum()),
        "Ensemble flags": int(bench[f"flag_ens_{m}"].sum())})
    rho, p = spearmanr(lps[ok], risk[ok])
    spear.append({"model": m, "spearman_rho": rho, "p_value": p,
                  **{f"tau={t}": int((risk[ok] > t).sum()) for t in [0.05, 0.10, 0.15, 0.20, 0.25, 0.30]}})
bench.to_csv(bench_path, index=False)
pd.DataFrame(log).to_csv(os.path.join(OUT_DIR, "table4_partitions.csv"), index=False)
display(pd.DataFrame(log).round(3)); display(pd.DataFrame(spear).round(4))

val sentence F1 by tau: {0.0: 0.9605, 0.01: 0.9605, 0.02: 0.9605, 0.03: 0.9597, 0.04: 0.9518, 0.05: 0.9309, 0.1: 0.7799, 0.15: 0.6891, 0.2: 0.5706, 0.25: 0.5303, 0.3: 0.504, 0.35: 0.4813, 0.4: 0.4547, 0.45: 0.4136, 0.5: 0.3765}
best tau: 0.0 | current: 0.0
Single-signal test AUROC: {'R_H': 0.972, '-logprob': 0.88, '1-LaBSE': 0.882}

,config,w_det/w_lp/w_sem,thr,precision,recall,f1,flag_%,auroc
0,Detector only,1.00/0.00/0.00,0.01,0.949,0.977,0.963,51.707,0.972
1,Det-Mild,0.50/0.30/0.20,0.08,0.916,0.938,0.927,51.475,0.971
2,Det-Heavy,0.70/0.20/0.10,0.06,0.941,0.962,0.951,51.376,0.977
3,LP-Heavy,0.20/0.60/0.20,0.09,0.812,0.940,0.872,58.137,0.938
4,Sem-Heavy,0.20/0.20/0.60,0.10,0.838,0.907,0.871,54.392,0.944
5,Uniform,0.33/0.33/0.33,0.09,0.879,0.938,0.907,53.629,0.961
6,Val-tuned,0.90/0.00/0.10,0.03,0.949,0.977,0.963,51.707,0.979

,Model,Family,Errors,Scored,Avg LogProb,LogProb/word,Avg words,% >=150 words,All 3,Det+LP,Det+LaBSE,LP+LaBSE,Det only,LP only,LaBSE only,None,Ensemble flags
0,nllb_600m,nllb,0,1485,-7.424,-0.671,11.684,0.000,6,22,1,6,22,412,12,1004,516
1,nllb_1.3b,nllb,0,1485,-6.796,-0.617,11.788,0.000,7,34,6,11,23,394,23,987,599
2,m2m_418m,m2m,0,1485,-10.445,-0.919,12.108,0.000,38,114,25,29,76,265,56,882,391
3,m2m_1.2b,m2m,0,1485,-9.053,-0.815,11.910,0.000,23,53,13,32,40,338,49,937,126
4,mbart50_m2m,mbart,0,1485,-8.108,-0.734,11.562,0.000,14,73,13,8,40,351,31,955,709
5,mbart50_m2o,mbart,0,1485,-7.862,-0.707,11.638,0.000,5,48,10,9,30,384,26,973,170
6,mt5_sin,mt5,0,1485,-12.102,-0.971,12.593,0.067,109,113,49,29,58,195,61,871,334
7,opus_mul_en,marian,0,1485,-10.816,-0.865,13.175,0.000,134,103,99,26,97,183,67,776,764

,model,spearman_rho,p_value,tau=0.05,tau=0.1,tau=0.15,tau=0.2,tau=0.25,tau=0.3
0,nllb_600m,-0.1030,0.0001,36,22,15,10,7,6
1,nllb_1.3b,-0.1323,0.0000,51,32,23,18,13,11
2,m2m_418m,-0.3031,0.0000,203,109,68,38,26,18
3,m2m_1.2b,-0.2152,0.0000,102,60,41,28,22,15
4,mbart50_m2m,-0.2482,0.0000,108,52,31,18,11,8
5,mbart50_m2o,-0.1756,0.0000,78,42,23,10,6,6
6,mt5_sin,-0.4366,0.0000,272,195,146,120,107,93
7,opus_mul_en,-0.3686,0.0000,362,262,219,188,168,154

In [20]:
TAU_GRID = np.round(np.r_[0.0, 0.01, 0.02, 0.03, 0.04, np.arange(0.05, 0.51, 0.05)], 2)
old = pd.read_csv(abl_path)
new = []
for seed in SEEDS:
    det, dtok = load_detector(PRIMARY, seed)
    vr, _, _ = detector_scores(det, dtok, val_df.sinhala, val_df.hypothesis)
    TAU[seed], sc = calibrate_tau(vr, val_df.label.values, grid=TAU_GRID)
    print(f"seed {seed}: tau = {TAU[seed]}  (val sentence F1 {sc[TAU[seed]]:.4f})")
    new += run_ablation(det, dtok, TAU[seed], seed, "full")
    del det; free_gpu()
json.dump({str(k): v for k, v in TAU.items()}, open(os.path.join(OUT_DIR, "tau.json"), "w"))
abl = pd.concat([pd.DataFrame(new), old[old.model != "full"]], ignore_index=True)
abl.loc[abl.model == "hypothesis_only", "flag_rate_%"] = np.nan   # old-grid tau; report threshold-free metrics only
abl.to_csv(abl_path, index=False)
display(abl.groupby(["model", "condition"])[[c for c in metric_cols if c in abl]].agg(["mean", "std"]).round(3))

seed 42: tau = 0.0  (val sentence F1 0.9605)
seed 43: tau = 0.0  (val sentence F1 0.9495)
seed 44: tau = 0.0  (val sentence F1 0.9578)

                                    tok_f1        auroc_RH        auroc_maxp  \
                                      mean    std     mean    std       mean
model           condition
full            mismatch_test          NaN    NaN      NaN    NaN        NaN
                original             0.841  0.002    0.970  0.002      0.992
                removed              0.295  0.004    0.507  0.028      0.655
                shuffled             0.314  0.003    0.540  0.007      0.627
hypothesis_only removed(train+test)  0.622  0.008    0.850  0.010      0.906

                                           flag_rate_%         \
                                       std        mean    std
model           condition
full            mismatch_test          NaN         NaN    NaN
                original             0.000      50.978  0.746
                removed              0.026     100.000  0.000
                shuffled             0.030     100.000  0.000
hypothesis_only removed(train+test)  0.013         NaN    NaN

                                    flag_%_matched_faithful         \
                                                       mean    std
model           condition
full            mismatch_test                         4.464  0.916
                original                                NaN    NaN
                removed                                 NaN    NaN
                shuffled                                NaN    NaN
hypothesis_only removed(train+test)                     NaN    NaN

                                    flag_%_mismatched_faithful
                                                          mean  std
model           condition
full            mismatch_test                            100.0  0.0
                original                                   NaN  NaN
                removed                                    NaN  NaN
                shuffled                                   NaN  NaN
hypothesis_only removed(train+test)                        NaN  NaN

In [21]:
for m in ["nllb_600m", "mt5_sin", "opus_mul_en"]:
    path, fam = MODELS[m]; tok_mt, mdl_mt = load_nmt(path, fam)
    src_lang, bos_fn = FAMILY[fam]
    if src_lang: tok_mt.src_lang = src_lang
    enc = tok_mt(bench.sinhala[:8].tolist(), return_tensors="pt", padding=True, truncation=True).to(DEVICE)
    kw = dict(num_beams=4, max_new_tokens=256, output_scores=True, return_dict_in_generate=True)
    if bos_fn: kw["forced_bos_token_id"] = bos_fn(tok_mt)
    with torch.no_grad():
        out = mdl_mt.generate(**enc, **kw)
    ntok = (out.sequences[:, 1:] != tok_mt.pad_token_id).sum(1).cpu().numpy()
    print(f"\n{m}\n  beam score/token: {out.sequences_scores.cpu().numpy().round(2)}")
    print(f"  our lp/token:     {(bench[f'lp_{m}'][:8].values / ntok).round(2)}")
    del mdl_mt, tok_mt; free_gpu()

nllb_600m
  beam score/token: [-0.47 -0.26 -0.39 -0.61 -0.48 -0.38 -0.31 -0.68]
  our lp/token:     [-0.64 -0.55 -0.57 -0.83 -0.63 -0.63 -0.5  -1.02]

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

mt5_sin
  beam score/token: [-0.29 -0.26 -0.8  -1.02 -0.72 -0.8  -0.3  -0.71]
  our lp/token:     [-2.82 -4.01 -4.44 -3.43 -3.85 -3.91 -3.23 -3.22]

opus_mul_en
  beam score/token: [-0.4  -0.32 -0.86 -0.66 -1.14 -0.92 -0.38 -1.02]
  our lp/token:     [-19.78 -24.46 -23.85 -31.8  -34.85 -31.39 -26.7  -31.63]

In [23]:
@torch.no_grad()
def gen_logprob(model, tok, family, texts, bs=4):
    src_lang, bos_fn = FAMILY[family]
    if src_lang: tok.src_lang = src_lang
    hyps, lps, check = [], [], None
    for i in tqdm(range(0, len(texts), bs), desc="Generate+score"):
        enc = tok(list(texts[i:i + bs]), return_tensors="pt", padding=True,
                  truncation=True, max_length=512).to(DEVICE)
        kw = dict(num_beams=4, max_new_tokens=256, output_scores=True, return_dict_in_generate=True)
        if bos_fn: kw["forced_bos_token_id"] = bos_fn(tok)
        out = model.generate(**enc, **kw)
        ts = model.compute_transition_scores(out.sequences, out.scores, out.beam_indices,
                                             normalize_logits=False)
        mask = out.beam_indices[:, :ts.shape[1]] >= 0
        seq = torch.where(mask, ts, torch.zeros_like(ts)).sum(1)
        lps += seq.cpu().tolist()
        hyps += [h.strip() for h in tok.batch_decode(out.sequences, skip_special_tokens=True)]
        if check is None:
            check = ((seq / mask.sum(1)).cpu().numpy().round(2), out.sequences_scores.cpu().numpy().round(2))
        del out, ts
    return hyps, np.array(lps), check

bench = pd.read_csv(bench_path)
det, dtok = load_detector(PRIMARY, PRIMARY_SEED)
for m, (path, fam) in MODELS.items():
    free_gpu()
    tok_mt, mdl_mt = load_nmt(path, fam)
    hyps, lps, chk = gen_logprob(mdl_mt, tok_mt, fam, bench.sinhala.tolist())
    del mdl_mt, tok_mt; free_gpu()
    old = bench[f"hyp_{m}"].astype(str).str.strip().values
    changed = np.where(np.array(hyps) != old)[0]
    bench[f"hyp_{m}"], bench[f"lp_{m}"], bench[f"err_{m}"] = hyps, lps, False
    if len(changed):
        r, mp, _ = detector_scores(det, dtok, bench.sinhala.iloc[changed], bench[f"hyp_{m}"].iloc[changed])
        bench.loc[changed, f"risk_{m}"], bench.loc[changed, f"maxp_{m}"] = r, mp
        bench.loc[changed, f"labse_{m}"] = labse_sim(bench.sinhala.iloc[changed], bench[f"hyp_{m}"].iloc[changed])
    print(f"{m}: lp/token {chk[0]}\n{' ' * len(m)}  beam     {chk[1]}\n  changed hyps: {len(changed)}")
    bench.to_csv(bench_path, index=False)   # saved after every model, safe to resume
del det; free_gpu()

Generate+score:   0%|          | 0/372 [00:00<?, ?it/s]

nllb_600m: lp/token [-0.47 -0.26 -0.39 -0.61]
           beam     [-0.47 -0.26 -0.39 -0.61]
  changed hyps: 0

Generate+score:   0%|          | 0/372 [00:00<?, ?it/s]

nllb_1.3b: lp/token [-0.45 -0.26 -0.44 -0.46]
           beam     [-0.45 -0.26 -0.44 -0.46]
  changed hyps: 0

Generate+score:   0%|          | 0/372 [00:00<?, ?it/s]

m2m_418m: lp/token [-0.51 -0.35 -0.38 -0.6 ]
          beam     [-0.51 -0.35 -0.38 -0.6 ]
  changed hyps: 0

Generate+score:   0%|          | 0/372 [00:00<?, ?it/s]

m2m_1.2b: lp/token [-0.48 -0.4  -0.34 -0.56]
          beam     [-0.48 -0.4  -0.34 -0.56]
  changed hyps: 0

Generate+score:   0%|          | 0/372 [00:00<?, ?it/s]

mbart50_m2m: lp/token [-0.4  -0.22 -0.52 -0.52]
             beam     [-0.4  -0.22 -0.52 -0.52]
  changed hyps: 1

Generate+score:   0%|          | 0/372 [00:00<?, ?it/s]

mbart50_m2o: lp/token [-0.4  -0.26 -0.46 -0.53]
             beam     [-0.4  -0.26 -0.46 -0.53]
  changed hyps: 0

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Generate+score:   0%|          | 0/372 [00:00<?, ?it/s]

OutOfMemoryError: CUDA out of memory. Tried to allocate 3.82 GiB. GPU 0 has a total capacity of 14.56 GiB of which 3.62 GiB is free. Including non-PyTorch memory, this process has 10.94 GiB memory in use. Of the allocated memory 9.38 GiB is allocated by PyTorch, and 1.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [24]:
import sys
# release memory still held by the crashed call
sys.last_traceback = sys.last_value = sys.last_type = None
for v in ["mdl_mt", "tok_mt", "det", "dtok"]:
    globals().pop(v, None)
free_gpu()

bench = pd.read_csv(bench_path)
det, dtok = load_detector(PRIMARY, PRIMARY_SEED)
for m in ["mt5_sin", "opus_mul_en"]:
    path, fam = MODELS[m]
    free_gpu()
    tok_mt, mdl_mt = load_nmt(path, fam)
    hyps, lps, chk = gen_logprob(mdl_mt, tok_mt, fam, bench.sinhala.tolist(), bs=1)
    del mdl_mt, tok_mt; free_gpu()
    old = bench[f"hyp_{m}"].astype(str).str.strip().values
    changed = np.where(np.array(hyps) != old)[0]
    bench[f"hyp_{m}"], bench[f"lp_{m}"], bench[f"err_{m}"] = hyps, lps, False
    if len(changed):
        r, mp, _ = detector_scores(det, dtok, bench.sinhala.iloc[changed], bench[f"hyp_{m}"].iloc[changed])
        bench.loc[changed, f"risk_{m}"], bench.loc[changed, f"maxp_{m}"] = r, mp
        bench.loc[changed, f"labse_{m}"] = labse_sim(bench.sinhala.iloc[changed], bench[f"hyp_{m}"].iloc[changed])
    print(f"{m}: lp/token {chk[0]}\n{' ' * len(m)}  beam     {chk[1]}\n  changed hyps: {len(changed)}")
    bench.to_csv(bench_path, index=False)
del det; free_gpu()

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Generate+score:   0%|          | 0/1485 [00:00<?, ?it/s]

mt5_sin: lp/token [-0.29]
         beam     [-0.29]
  changed hyps: 0

Generate+score:   0%|          | 0/1485 [00:00<?, ?it/s]

opus_mul_en: lp/token [-0.4]
             beam     [-0.4]
  changed hyps: 0

## 8. Export

Zip the saved detector checkpoints and result tables. `benchmark_outputs.csv` is the input to *External Validation.ipynb* (COMET correlations and human-annotation sample).

In [26]:
shutil.make_archive(os.path.join(OUT_DIR, "detector_checkpoints"), "zip", MODEL_DIR)
for f in sorted(os.listdir(OUT_DIR)):
    if f.endswith((".csv", ".json", ".zip")):
        print(f)

benchmark_outputs.csv
chosen_ensemble.json
detector_checkpoints.zip
signals_test.csv
signals_val.csv
split_test.csv
split_train.csv
split_val.csv
table3_detector.csv
table4_partitions.csv
table5_ensemble.csv
table_source_ablation.csv
tau.json